# Generated by Django 4.2.1 on 2023-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('source_page', models.TextField(blank=True, null=True)),
                ('date_of_account_creation', models.DateTimeField(blank=True, null=True)),
                ('fake_probability', models.FloatField(blank=True, null=True)),
                ('priority_level', models.CharField(choices=[('1', 'Very Low'), ('2', 'Low'), ('3', 'Medium'), ('4', 'High'), ('5', 'Very High')], default='3', max_length=1)),
            ],
            options={
                'order_with_respect_to': 'priority_level',
            },
        ),
    ]
