# Generated by Django 4.2.1 on 2023-05-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvertisement',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
